name: Docs

on: [push, pull_request]

jobs:
  docs:
    name: Docs

    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
    container: osgeo/proj-docs

    steps:
    - uses: actions/checkout@v4
    - name: Print versions
      shell: bash -l {0}
      run: |
          python3 --version
          DEBIAN_FRONTEND=noninteractive apt-get update --assume-yes
          DEBIAN_FRONTEND=noninteractive apt-get install pandoc texlive-xetex --assume-yes
          pip3 install pandoc
          sphinx-build --version
    - name: Lint .md files
      shell: bash -l {0}
      run: |
        if find . -name '*.md' | xargs grep -P '\t'; then echo 'Tabs are bad, please use four spaces in .md files.'; false; fi
    - name: HTML
      shell: bash -l {0}
      run: |
        pandoc -s README.md -o README.html

    - name: PDF
      shell: bash -l {0}
      run: |
        pandoc -s README.md -o README.pdf  --pdf-engine=xelatex

    - uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: README.pdf
    - uses: actions/upload-artifact@v4
      with:
        name: HTML
        path: README.html

